### ISSUE TITLE
Error during "meson build"

### ISSUE THREAD

**Issue by devnix** [jorchube/vest#1]
I'm trying to learn how to integrate Vest into my project while I learn Vala again, and I'm getting the following output:

```
The Meson build system
Version: 0.58.1
Source dir: /home/devnix/tmp/vest
Build dir: /home/devnix/tmp/vest/build
Build type: native build
Project name: io.github.jorchube.vest
Project version: undefined
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.48.6)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library posix found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gio-2.0 found: YES 2.64.6
Run-time dependency gee-0.8 found: YES 0.20.3
Run-time dependency libxml-2.0 found: YES 2.9.10
Program /home/devnix/tmp/vest/build/io.github.jorchube.vest.tests found: NO

meson.build:72:0: ERROR: Program '/home/devnix/tmp/vest/build/io.github.jorchube.vest.tests' not found
```

**Comment by jorchube** [comment]
Hi there!

I am not sure what have you tried (the exact commands and such), so I'm not sure if I will be able to help you.

Anyway, I have been reviewing the templates that I provide with the project and I have made a new [release 0.1.1](https://github.com/jorchube/vest/releases/tag/0.1.1) with a few changes to be able to build and run the provided sample test without modifications. So If you do this:

```
curl -LkO "https://github.com/jorchube/vest/releases/download/0.1.1/vest-release-0.1.1.tar.gz"
tar xvf vest-release-0.1.1.tar.gz 
cd templates/
meson build
ninja -C build
./build/some.project.tests
```

without any modification, you should be able to execute the dummy test provided in the templates folder with an output similar to this:

```
Test Suite: somenamespaceMyTestSuite
  ✔ Should_pass : PASSED : 0.005 ms
1 PASSED 0 FAILED 0 IGNORED
------------------------------
```
If that works you can start toying with the `meson.build` template file or take it as a reference to see how to add the compiled Vest library to your project.

Otherwise if you are trying to integrate Vest by using directly the source files you can take a look at the Vest `meson.build` itself and how it builds the library or you can just add your sources and the Vest sources together to compile the tests.

If what you have tried is to just compile Vest itself and run the tests, it should work out of the box with the following commands:

```
git clone https://github.com/jorchube/vest.git
cd vest/
meson build
ninja -C build
./build/io.github.jorchube.vest.tests
```


I hope this will help.

**Comment by devnix** [comment]
Hi! Thank you for your fast answer!

The command that is failing to me is `meson build`, I've just upgraded to 0.1.1 and I still have the same problem:

![image](https://user-images.githubusercontent.com/1777519/125071442-8f23ed00-e0b9-11eb-8dbf-bebb7e0ff8e6.png)

**Comment by devnix** [comment]
Found it, so this lines were blocking me on a fresh compilation from `meson.build`

```meson
test_exe_path = meson.current_build_dir() + '/' + meson.project_name() + '.tests'

run_target(
    'run_tests',
    command: [test_exe_path],
    depends: libvest_tests
)
```

After commenting them, I've been able to compile and run the software!

**Comment by jorchube** [comment]
I see.

Glad that you found a solution.

Thanks to your input I have updated the README to try to give more insight to get started and also I've deleted the `run_target` that gave you problems in the `meson.build` template as it is not needed at all.

Thank you for giving Vest a try! :)

**Comment by devnix** [comment]
Nice! but the problem was on `meson.build`, IDK what is for `templates/meson.build`, but I think the problem will remain if it's not removed from `meson.build`

**Comment by jorchube** [comment]
Aha! I though you were trying the build the sample project. I didn't even realize that the same think could happen in the `meson.build`.

Actually I have not been able to reproduce your issue either way, but since it is not necessary at all and maybe it happens due to whatever configuration a specific distribution has, just deleting it seems fine to me.

Thank you very much for your contribution! :1st_place_medal:

**Comment by devnix** [comment]
It's easy, just do a fresh clone. Maybe it's not that and we are differing on the Meson version, I'm still very novice on this field.

Can I contact you in some way to ask a couple of questions about this repo in private? You can ping me at the mail indicated in my profile.

Thank you so much!

PS: You can reach me on Vala's Discord server too :D
